language: go

script: make test

before_install:
   - go get github.com/gorilla/handlers
   - go get github.com/docopt/docopt-go
   - go get github.com/fatih/color
   - go get github.com/rjeczalik/notify
go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip
